pipeline {
    agent {label 'staging'}
    stages {
        stage('Deploy'){
            steps{
                sh "sudo pm2 stop all"
                sh "sudo pm2 start src/index.js"
                sh "sudo pm2 save"
                sh "sudo pm2 startup"
                
            }
        }
    }
}