---

- hosts: staging
  tasks:

  - name: update nodejs package 
    command: curl -fsSL https://deb.nodesource.com/setup_15.x | sudo -E bash -

  - name: install nodejs
    apt:
        name: nodejs
        state: present
  
  - name: Creates directory
    file:
      path: /src/www
      state: directory

  - name: getting artifact
    ansible.builtin.unarchive:
      src: http://10.0.0.4:8080/job/weightCI/lastSuccessfulBuild/artifact/latest.zip
      dest: /src/www
      remote_src: yes         

  - name: creat .env
    command: bash buildEnv.sh -u {{ hostvars['staging'].okta_url }} -i {{ hostvars['staging'].okta_id }} -s {{ hostvars['staging'].okta_secret }} -h {{ hostvars['staging'].db_host }} -p {{ hostvars['staging'].db_pass }} -n {{ hostvars['staging'].db_user }}

  - name: initialize db
    command: node /src/www/tools/initdb.js

  - name: run app
    command: node /src/www/src/index.js
